export { MainTabsProvider, useMainTabs } from "./context"
export type { MainTab, ThreadMainTab, FileMainTab } from "./context"
export { MainTabBar } from "./components/main-tab-bar"
export { FileContentView } from "./components/file-content-view"
export { TabsEmptyState } from "./components/tabs-empty-state"
